services:
  app:
    build:
      dockerfile: ./docker/app/Dockerfile
      target: local
    container_name: qr-parking
    restart: always
    ports:
      - "127.0.0.1:8002:8090"   # только локально, хостовый Nginx будет сюда проксировать
    volumes:
      - ./:/usr/src/app
    networks:
      - qr-parking-network
    depends_on:
      - database
      - cache

  database:
    image: postgres:16-alpine
    container_name: qr-parking-database
    restart: always
    # ports — убраны, снаружи не нужны
    volumes:
      - postgres-data-main:/var/lib/postgresql/data
      - ./docker/postgres/postgresql.conf:/etc/postgresql.conf
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
    env_file:
      - docker/postgres/.db.env
    networks:
      - qr-parking-network

  cache:
    image: redis
    container_name: qr-parking-redis
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    env_file:
      - docker/redis/.redis.env
    networks:
      - qr-parking-network

volumes:
  postgres-data-main:

networks:
  qr-parking-network:   # compose создаёт сам, не external